apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: default
  labels:
    release: kube-pro-stack
  name: ml-api
spec:
  endpoints:
    - path: /metrics
      port: ml-api
      scheme: http
      interval: 30s

  jobLabel: ml-api
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: ml-api
