apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-api
  labels:
    app: ml-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-api
  template:
    metadata:
      labels:
        app: ml-api
    spec:
      containers:
        - name: ml-api
          image: dlinguist/ml-app:latest
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3-env
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-env
                  key: AWS_SECRET_ACCESS_KEY
            - name: MLFLOW_S3_ENDPOINT_URL
              valueFrom:
                secretKeyRef:
                  name: s3-env
                  key: MLFLOW_S3_ENDPOINT_URL
            - name: MLFLOW_TRACKING_URI
              valueFrom:
                secretKeyRef:
                  name: s3-env
                  key: MLFLOW_TRACKING_URI
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: s3-env
                  key: AWS_REGION
          ports:
            - containerPort: 8000
